import type { Href } from 'expo-router';

export interface LocationPickerParams {
  /** `current` sets the delivery location (the default); `add` saves another address. */
  mode?: 'current' | 'add';
  /** Open with the search field focused. */
  start?: 'search';
  /** Centre here — a GPS fix taken before opening. */
  lat?: number | null;
  lng?: number | null;
}

/**
 * The route to the full-screen map picker. Route params are strings, so the
 * numbers are stringified here and parsed back on the screen.
 */
export function locationPickerHref({ mode, start, lat, lng }: LocationPickerParams = {}): Href {
  const params: Record<string, string> = {};
  if (mode) params.mode = mode;
  if (start) params.start = start;
  if (lat != null && lng != null) {
    params.lat = String(lat);
    params.lng = String(lng);
  }
  // Typed routes are regenerated by `expo start`; the cast keeps a fresh
  // checkout compiling before that has run once.
  return { pathname: '/location-picker', params } as unknown as Href;
}
