/**
 * UI primitives.
 *
 * Hand-written on NativeWind against `lib/tokens.js` rather than generated by
 * the `react-native-reusables` CLI: rnr's components assume shadcn-style HSL
 * CSS variables in `global.css`, whereas this app styles with direct-hex
 * scales (`bg-brand-500`, `bg-surface-muted`) already used across every screen.
 * Adopting rnr would have meant maintaining two theming conventions at once.
 * The API surface below mirrors rnr's, so swapping later is mechanical.
 */
export { Button, type ButtonVariant, type ButtonSize } from './Button';
export {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from './Card';
export { Badge, type BadgeVariant } from './Badge';
export { Skeleton, SkeletonText, SkeletonCard } from './Skeleton';
export { Input } from './Input';
export { Stepper } from './Stepper';
export { Tabs, type TabItem } from './Tabs';
export { Sheet } from './Sheet';
export { Dialog, AlertDialog } from './Dialog';
export { Avatar } from './Avatar';
export { Separator } from './Separator';
export { EmptyState, ErrorState, InlineError } from './States';
